version: '3.4'

services:
  monvieuxgrimoirefrontend:
    image: monvieuxgrimoirefrontend
    build:
      context: Frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
